name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Docker Credentials
      uses: docker/login-action@v3
      with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Github (GHCR) Registry Login
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag seshadrisv/ecom-web:v1 

    - name: Docker Push to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
           ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
           ghcr.io/${{github.repository_owner}}/solar-system:${{github.sha}}
